### ISSUE TITLE
Site is not parsed properly

### ISSUE THREAD

**Issue by ivanicin** [zzzprojects/html-agility-pack#1]
This page is not parsed like in browsers: http://chandra.harvard.edu/photo/2015/ngc6388/ 

I believe that the cause are 'learn' tags that are not closed (which causes then their parent <p> tags to be removed).

**Comment by JonathanMagnan** [comment]
Hello @ivanicin ,

Thank you for reporting.

We will try to investigate this issue during the weekend and try to come back with a solution next Monday.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @ivanicin ,

We started to investigate the issue.

The current problem is the "p" is not handled like a normal tag. See: https://github.com/zzzprojects/html-agility-pack/blob/master/src/HtmlAgilityPack/HtmlNode.cs#L118

Something that both me a lot is when I read the following comment:
> &lt;p&gt;bla&lt;p&gt;bla will be transformed into &lt;p&gt;bla&lt;p&gt;bla and not &lt;p&gt;bla&gt;&lt;/p&gt;&lt;p&gt;bla&lt;/p&gt; or &lt;p&gt;bla&lt;p&gt;bla&lt;/p&gt;&lt;/p&gt;

I would have expected the following scenario `<p>bla></p><p>bla</p>`, certainly not the "p" remain unchanged!

A `p` tag cannot contain another `p` tag, so it should close automatically the previous one. 

Anyway, since the `learn` tag is unclosed, and `p` tag doesn't work like other tags, the `learn` tag is closed to the closest parent which is the `div` element instead of the `p` tag.

That's what is currently happening.

We are continuing our investigation.

Best Regards,

Jonathan

**Comment by ivanicin** [comment]
Hi,

thanks for your feedback. For now I found a workaround (detecting the problem and using web browser to get the properly parsed content in that case), which isn’t perfect - for example Apple TV has no browser and this also slows down everything.

Best regards,
Ivan Icin
Labsii

ivan.icin@labsii.com 
www.labsii.com

**Comment by JonathanMagnan** [comment]
Hello @ivanicin ,

We didn't successfully fixed the issue yet but today we will release a new version.

In this version, an option will be added to make the `p` tag act like a `div` and `span` tag.

Until we re-write the parser, I believe this will be a good alternative for you.

This version should be available in a few hours.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @ivanicin ,

The v1.5.0-beta3 has been released:
https://www.nuget.org/packages/HtmlAgilityPack/1.5.0-beta3

We added a temporary fix, you can read it more in detail here:
https://github.com/zzzprojects/html-agility-pack/releases/tag/v1.5.0-beta3

Could you confirm us if this temporary fix is working?

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Closing comment: No confirmation, feel free to re-open if you still have the issue.

**Comment by chrisnelsondotca** [comment]
Hi @JonathanMagnan,

I believe I'm seeing a related issue in 1.5.1 - When encountering a P block with no content, HAP will remove the closing P. For example:
Starting HTML: <p style="font-size:1px;"></p><p>test</p>
HTML after HAP: <p style="font-size:1px;"><p>test</p>

Using HtmlAgilityPack.HtmlDocument.DisableBehavaiorTagP = true; seem to resolve this issue. Should we expect to continue to use that option in future releases?

**Comment by JonathanMagnan** [comment]
Hello @chrisnelsondotca ,

I'm currently right now looking how to fix all this kind of issue. People report them with `p`, `a`, etc.

The current library seems to doesn't work well when the HTML is badly formatted with some kind of tag.

btw, please try to ask or report a issue/question on a new thread, it makes easier on my side to follow them. By example, since this thread is closed, there is not a lot of chance that I will answer to it once it fixed.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
You can easily reference an issue by simply adding the issue number...

Ex: Issue #1

**Comment by chrisnelsondotca** [comment]
Hi @JonathanMagnan thank you, I appreciate the response. Should I create a new issue referencing this one then?

**Comment by JonathanMagnan** [comment]
Please yes ;) So this issue could stay closed.
