### ISSUE TITLE
Please add net46 dll in the Nuget

### ISSUE THREAD

**Issue by damageboy** [zzzprojects/html-agility-pack#119]
Hi,
I'm having a weird problem with a project that uses multi target frameworks and HAP
Here's a repro:
https://github.com/damageboy/haptest

You'll notice that the .csproj uses:

`<TargetFrameworks>netcoreapp2.0;net462</TargetFrameworks>`

This means that the project will compile TWICE, once per framework.

Unfortunately, this means that `dotnet restore` will use the `netstandard2.0` dll from the HAP nuget when compiling for `netcoreapp2.0`, BUT the `net45` dll when compiling for net462.

This would all be fine, if the `net45` and `netstandard2.0` would actually be equal.. but guess what... they are not:

The net45 version exposes this delegate:
```
public delegate void PostResponseHandler(HttpWebRequest request, HttpWebResponse response);
```

While the netstandard2.0 version exposes this one:
```
public delegate void PostResponseHandler(HttpRequestMessage request, HttpResponseMessage response);
```

This means that I would have to use #if pragmas sprikled all over my code to get this working..

I think it would be very useful to provide a net462/net46 version inside the .dll so that project tha ARE targeting both frameworks can use the same API...

**Comment by JonathanMagnan** [comment]
Hello @damageboy ,

Welcome to my world where I need to add multiple `#if` compilation debug ;)

The problem will be the same for `net46`, people will want to have the same API as the `net45` since method are available.

The `NETSTANDARD` simply doesn't provide the same API as the full `.NET Framework`, so there is not a lot of things we can do on our side until more `API` is available.

The good news is `HttpWebRequest` was not available in `NETSTANDARD1_3` but look to be available in `NETSTANDARD_20`, so we will review the code and expose now some method that can be available.

We will try to make changes this week.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by damageboy** [comment]
Thanks, I mainly want the user facing API to be stable.

I of course understand the tremendous effort required inside the library to provide this consistent facade.

One thing I don't entire understand though, is the following:
Isn't `HttpRequestMessage` and `System.Net.Http` available to .NET 4.5 as well?

In theory, unless I'm completely off base, even the .NET 4.5 could expose that API, while exposing the older API to .NET 4.0 users and below.

Additionaly, or alternatively, perhaps you should just decide to leave things as they are and release HAP 2.0 while dropping everything that isn't based on `System.Net.Http`

Kind of create an artificial split with 1.x being "Old" API, while 2.x being newer API.

That way, you have two branches, a 1.x and 2.x branch, where 1.x eventually dies together with the last dinosaurs still producing .NET 2.x and .NET 4.0 binaries.

I mean, after all, even .NET 4.5 is already dead:
https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/

Maybe its just time to move on?

**Comment by JonathanMagnan** [comment]
Hello @damageboy ,

The v1.7.0 has been released.

Some **breaking changes** has been released to make the API compatible with FX45.

The old code was done because NETSTANDARD1_3 && NETSTANDARD1_6 doesn't support most API NETSTANDARD2_0 support.

I believe the way we did it was the best on long-term even if that break some code for people using HAP under NETSTANDARD2_0 to force them to use it as they were previously doing on FX45.

Best Regards,

Jonathan
