### ISSUE TITLE
when using htmldocument.LoadFromBrowser thrown the following exception

### ISSUE THREAD

**Issue by mrtylerzhou** [zzzprojects/html-agility-pack#124]
ThreadStateException: ActiveX control '8856f961-340a-11d0-a96b-00c04fd705a2' cannot be instantiated because the current thread is not in a single-threaded apartment.

**Comment by JonathanMagnan** [comment]
Hello @mrtylerzhou ,

Are you using the method `LoadFromBrowser`? If that's the case, it cannot work for this kind of project.

Unfortunately, this is a limitation of the `WebBrowser` and there is not so much we can do.

The only way to work around this issue is to create a new thread with `STA`

If you search for it and find a good please, please try to report it here to improve this answer.

Best Regards,

Jonathan

---
_Help us to keep this library free: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by mrtylerzhou** [comment]
@JonathanMagnan  Thank you for your explaination,I'll try it.I have no better ways.I just tried it following the document in the official site and came across with this problem.

**Comment by JonathanMagnan** [comment]
Hello @mrtylerzhou ,

I will close this issue since I believe there are no more activities to do on it.

Feel free to reopen it if you believe it should not have been closed.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by mrtylerzhou** [comment]
of course

**Comment by banjahman** [comment]
for anyone looking to get around this error, I ran into it using a C# web api, and was able to get around this error using the following pattern

```HtmlDocument doc = null;  
var t = new Thread(() => {  
    var web = new HtmlWeb();
    doc = web.LoadFromBrowser(href, o => {
        return true;
    });
});
t.SetApartmentState(ApartmentState.STA);
t.Start();
while (doc == null) {
    Task.WaitAll(Task.Delay(1000));
}
