### ISSUE TITLE
Does it support .net core ??

### ISSUE THREAD

**Issue by tavisca-arvindy** [zzzprojects/html-agility-pack#13]

**Comment by JonathanMagnan** [comment]
Hello @tavisca-arvindy ,

Since the v1.5.0, the library support .NET Core for NETSTANDARD 1.6

Let me know if that answer correctly to your question.

Best Regards,

Jonathan

**Comment by pendenaor** [comment]
Hi,
The nuget seems broken, it targets netcore **4.5**, which does'nt exists.

**Comment by pendenaor** [comment]
May i ask you if NetStandard 1.6 is truly needed ?

**Comment by JonathanMagnan** [comment]
> it targets netcore 4.5, which does not exist.

That was for Metro application which supports .NET "Core" 4.5 (Target Windows 8)

It was before the .NET Core we know today. 

> May i ask you if NetStandard 1.6 is truly needed?

It's for sure needed. That's the version that is used with .NET Core

Or perhaps I misunderstood your question?

Best Regards,

Jonathan

**Comment by pendenaor** [comment]
> > May i ask you if NetStandard 1.6 is truly needed?
> 
> It's for sure needed. That's the version that is used with .NET Core
> 
> Or perhaps I misunderstood your question?

My own lib, which depends on HAP, is NetStandard 1.1 and i would not want to rise it to 1.6.
Do you have some guidance about that?

**Comment by JonathanMagnan** [comment]
The problem about .NETStandard 1.1 is almost nothing is supported that library requires.

By example, 3 of 4 packages on which HAP depend require .NETStandard 1.3 minimum:

- https://www.nuget.org/packages/System.Xml.XmlDocument/
- https://www.nuget.org/packages/System.Xml.XPath/
- https://www.nuget.org/packages/System.Xml.XPath.XmlDocument/

So it could be possible to create a .NETStandard 1.3 packages but 1.1 will be close to impossible I believe since we don't have access to package required.

If we remove theses dependencies, I'm not sure how many functionalities we will remove!

We will soon support CSS Selectors like jQuery. Perhaps after we support it, I could check to see about the support for 1.1

You will not have access to XPath selectors, but at least you will have access to CSS Selectors.

Best Regards,

Jonathan

**Comment by pendenaor** [comment]
Thanks for your thorough answer.
Thinking back on it, NetStandard 1.3 sounds good to me.

Best regards,
Stéphane.

**Comment by JonathanMagnan** [comment]
Great, we will try to support .NET Standard 1.3 during the weekend.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @pendenaor ,

We added support to the .NET Standard 1.3,

The new version should be available within a few hours.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @jonalbrecht ,

The version v1.5.0-beta9 has been released:
https://www.nuget.org/packages/HtmlAgilityPack/1.5.0-beta9

Let us know if the support to .NET Standard 1.3 work correctly

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Closing Comment: Feel free to re-open if you still have an issue.

**Comment by JonathanMagnan** [comment]
Hello @doggy8088 ,

I have created a new issue to clean up dependencies on next release: https://github.com/zzzprojects/html-agility-pack/issues/274

Since there are no dependencies on this framework, even if we continue to support it, we can hide it from the `Dependencies` section.

As you said, `NETCore 4.5` is really confusing and I don't think it will bother anyone that this framework doesn't appear in that page section.

Thank for your suggestion.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
