### ISSUE TITLE
EncapsulatorCompatibility

### ISSUE THREAD

**Issue by parsalotfy** [zzzprojects/html-agility-pack#158]
Hello
3 month ago I have pulled a request named [Encapsulator](https://github.com/zzzprojects/html-agility-pack/pull/109) and you accept it.
Now I wanna add some exception handling and clean it up.
but I don't know which versions of .Net should my code be compatible with.
for example in last version of Encapsulator we have this code :
```
#if !(NETSTANDARD1_3 || NETSTANDARD1_6)
            properties = type.GetProperties();
#endif


#if NETSTANDARD1_3 || NETSTANDARD1_6
            properties = type.GetTypeInfo().GetProperties();
#endif
```

should I continue writing code with this way ?
or **if old versions are not so important , please let me know , then I can use new .Net features like LINQ and some new Reflection  features.**

OR please let me know , if writing Exception handling is not a good idea.

Thank you in advance.
Parsa

**Comment by JonathanMagnan** [comment]
Hello @parsalotfy ,

Supporting old version is somewhat important. If we can do it, then we do it but otherwise, we add features only for .NET45 and upward (such as when adding Async method)

I'm not sure exactly what you want to add but just go ahead and in the worse case, we will either ask you to make some changes or do them on our side.

And thank again for contributing to this library ;)

Best Regards,

Jonathan
