### ISSUE TITLE
Make SelectNodes() behaviour consistent with Linq

### ISSUE THREAD

**Issue by alexholy** [zzzprojects/html-agility-pack#177]
Depending on the input SelectNodes() results in a sequence or null. There should be no null case (instead an empty sequence should be returned)

```C#
var doc1 = "<div><p>1</p><p>2</p></div>";
var doc2 = "<div></div>";

// XPath/Linq example to show expected behaviour

var n1 = XDocument.Parse(doc1)
	.XPathSelectElements("/div/p")
	.Count();

var n2 = XDocument.Parse(doc2)
	.XPathSelectElements("/div/p")
	.Count();

// Html Agaility pack behaviour

var doc = new HtmlDocument();
doc.LoadHtml(doc1);
var h1 = doc.DocumentNode
	.SelectNodes("/div/p")
	.Count();

// this should work and report 0
// beacuse this does not work you have to break apart everything
// after SelectNodes() and check for a null result
doc = new HtmlDocument();
doc.LoadHtml(doc2);
var h2 = doc.DocumentNode
	.SelectNodes("/div/p")
	.Count();
```

**Comment by JonathanMagnan** [comment]
Hello @alexholy ,

I agree with you. However, the default behavior since the last 13 years has been to return `null`.

An option was added some month ago `OptionEmptyCollection` to fix this issue.

```csharp
var doc = new HtmlDocument();
doc.OptionEmptyCollection = true;
```

I understand that returning an empty collection should have been done in the first place but making the fix will break so many codes that we prefer not doing it.

Best Regards,

Jonathan
