### ISSUE TITLE
HtmlDocument HtmlEncode

### ISSUE THREAD

**Issue by Carignan** [zzzprojects/html-agility-pack#190]
in HtmlDocument ,cs 

Is there a reason why HtmlEncode do not use standard **System.Web.HttpUtility.HtmlEncode** or even better the **System.Web.Security.AntiXss.HtmlEncode** function?

**Comment by JonathanMagnan** [comment]
Some method still exists and have not been modifying due to some backward compatibility reason.

I may be wrong but I believe these methods have not been initially used because the reference (System.Web) doesn't exist in all project types supported.

So the original author makes his own method.

We still cannot use these methods since not all projects type supports this namespace. So having the same method returning different result depending on the project type will not be a good solution either.

I hope that answer to your question.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @JorgenLindell ,

While you have a very good workaround, the question is more if coding this kind of feature is really needed since it takes some time (not a lot I agree).

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @JorgenLindell ,

This issue will be closed since I don't think there is a need to do something on it on our side. It's currently working even if it's not the best solution.

Best Regards,

Jonathan
