### ISSUE TITLE
Lower casing case sensitive SVG attributes. 

### ISSUE THREAD

**Issue by PokerPro123** [zzzprojects/html-agility-pack#199]
HAP is lower casing ALL attributes including case sensitive SVG attributes. 

I use this library to insert/edit different HTML nodes. However, I cannot have it unintentionally changing the original content. 

The viewBox attribute is case sensitive. 

**Source**: 
```
		<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="100%" height="100%" viewBox="0 0 600 800">
			<rect x="0" y="0" fill="#000007" width="600" height="100%"></rect>
			<image width="600" height="800" xlink:href="images/cover.jpg" transform="translate(0 0)"></image>
		</svg>
```
**Output**: 
```
		<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="100%" height="100%" viewbox="0 0 600 800">
			<rect x="0" y="0" fill="#000007" width="600" height="100%"></rect>
			<image width="600" height="800" xlink:href="images/cover.jpg" transform="translate(0 0)"></image>
		</svg>
```

**Comment by JonathanMagnan** [comment]
Hello @PokerPro123 ,

Thank you for reporting, we will look at what we can do to keep some attribute without modifying the case. I'm not sure if that will be possible since a lot of logic are assuming code is in lowercase.

Best Regards,

Jonathan

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @PokerPro123 ,

The v1.8.4 has been released. We finally choose to add a new method named `UseAttributeOriginalName`.

For Example:

```csharp
var doc = new HtmlAgilityPack.HtmlDocument();

doc.LoadHtml(@"<svg version=""1.1"" xmlns=""http://www.w3.org/2000/svg"" xmlns:xlink=""http://www.w3.org/1999/xlink"" width=""100%"" height=""100%"" viewBox=""0 0 600 800"">
<rect x=""0"" y=""0"" fill=""#000007"" width=""600"" height=""100%""></rect>
<image width=""600"" height=""800"" xlink:href=""images/cover.jpg"" transform=""translate(0 0)""></image>
</svg>");


doc.UseAttributeOriginalName("svg");
```

All name for the `svg` tagName will use the OriginalName instead of the lower name. This options can have some side effect however in some other part of the library if you search some attribute from the `svg` tag name.

Let me know if that solves your issue.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @PokerPro123 ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan

**Comment by zimmer62** [comment]
This doesn't seem to help if you're adding attributes to your own new svg child elements

```
  HtmlNode wrapperSvgNode = HtmlNode.CreateNode("<svg></svg>");
  wrapperSvgNode.SetAttributeValue("viewBox", "0 0 100 100");
```
