### ISSUE TITLE
parse simple html string has bug

### ISSUE THREAD

**Issue by tiandian** [zzzprojects/html-agility-pack#201]
when use the version "1.8.2", parse simple html string has bug.
see below code:
```
            HtmlDocument doc = new HtmlDocument();
            string v = @"
<form>
    <div>
        <table>
            <tr>
                <td></td>
                <td colspan='3'><textarea /></td>
            </tr>
            <tr>
                <td colspan='4'>
                    <div>
                    </div>
                </td>
            </tr>
        </table>
    </div>
</form>";

            doc.LoadHtml(v);
            System.Diagnostics.Debug.Print(doc.DocumentNode.OuterHtml);
```

the Debug.Print show the below result:

```
<form>
    <div>
        <table>
            <tr>
                <td></td>
                <td colspan='3'><textarea></textarea></td></tr></table></div></form>
```

lost the second tr row.

when use the old version "1.5.2-beta6", it has not  this bug.

**Comment by JonathanMagnan** [comment]
Hello @tiandian ,

We started to investigate this issue but unfortunately fixing it would probably not solve your problem.

The `TextArea` element cannot be closed like this. An explicit `</textarea>` is required otherwise all following HTML until a `</textarea>` or end of the document will be assumed to be the textarea value.

You can easily test this scenario by creating an HTML and adding your code. You will see the textarea value content all the remaining `HTML`.

The `1.5.2-beta6` has not this bug because the textarea was not parsed correctly.

You can restore the old behavior by removing the ElementsFlags like this

```csharp
HtmlNode.ElementsFlags.Remove("textarea");

doc.LoadHtml(v);
var s = doc.DocumentNode.OuterHtml;
```

Let me know if that explains this behavior correctly and if the proposed solution works for you.

Best Regards,

Jonathan

**Comment by tiandian** [comment]
@JonathanMagnan, i see. 
after i change "<textarea />" to "<textarea></textarea>", then it works.
thanks!
