### ISSUE TITLE
Encoding detected, but got wrong node inner value

### ISSUE THREAD

**Issue by Waynezhi** [zzzprojects/html-agility-pack#202]
Hello,

i use Load(stream, true) to load a page, and encoding is ok but when i parse a value from a specific node, wrong encoding inside.

example page: https://item.jd.com/1595987422.html

thanks for your help.

**Comment by JonathanMagnan** [comment]
Hello @Waynezhi ,

Do you think you could provide us a project example/test with this issue?

It will make easier/faster for my developer to getting started for investigating it.

_We now always ask for a project since we found out that most issues are missing some essential information or are resolved by the requestor when creating it_

_(Even if the issue seem very easy to reproduce, by getting a test project, it allow us to give a faster support and better experience for the support of all our free libraries)_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by Waynezhi** [comment]
[ConsoleApp2.zip](https://github.com/zzzprojects/html-agility-pack/files/2023976/ConsoleApp2.zip)
here is an example, i have to parse web response stream from another code.

**Comment by JonathanMagnan** [comment]
Thank you,

The task has been assigned to my developer.

**Comment by Waynezhi** [comment]
Hey @JonathanMagnan ,

i think that is a copy/paste error, and what i got from title for https://item.jd.com/1595987422.html is ¿­×¿£¨KENZO£© ´¿¾»Ö®Ë®Å®ÓÃµ­ÏãË®£¨Ë®Ö®Áµ£© µ­Ïã·Õ ³Ö¾ÃÁôÏã 30ml¡¾Í¼Æ¬ ¼Û¸ñ Æ·ÅÆ ±¨¼Û¡¿-¾©¶«
which is not in correct chinese encoding, the correct should be: 凯卓（KENZO） 纯净之水女用淡香水（水之恋） 淡香氛 持久留香 30ml【图片 价格 品牌 报价】-京东

**Comment by JonathanMagnan** [comment]
Thank you for the additional information, now I understand what you mean.

I will re-assign this request to my developer.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Waynezhi ,

Unfortunately, it seems the StreamReader we use cannot detect the encoding correctly for the stream provided..

The only options for you are to specify yourself the encoding in this case:

```csharp
htmlDoc.Load(stream, Encoding.GetEncoding("gbk"));
```

We didn't find any alternative solutions at this moment.

Best Regards,

Jonathan

**Comment by Waynezhi** [comment]
ok, thanks for your response.
