### ISSUE TITLE
Extra .NETStandard1.3 entry in nuspec file

### ISSUE THREAD

**Issue by lukecolburn** [zzzprojects/html-agility-pack#22]
The .nuspec file for 1.5.0-beta9 has an extra .NETStandard1.3 group entry without any of the necessary dependencies. Nuget chose this entry instead of the one below it, so it didn't install the dependencies HAP needs.

![image](https://user-images.githubusercontent.com/23244710/27344673-c000b8a0-55ac-11e7-8539-7e68a5d1a980.png)

**Comment by JonathanMagnan** [comment]
Hello @lukecolburn ,

Thank you for reporting.

That's a very strange error, we will try tomorrow if we can replicate it and fix it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @lukecolburn ,

I simply released without modifying nothing and it appears the issue has been fixed by itself (I was also getting it in the v1.5.0-beta9)

The v1.5.0-beta90 has been released
https://www.nuget.org/packages/HtmlAgilityPack/1.5.0-beta90

We had to add a "0" since it appears beta10 would appear below "beta2" since it's ordered by name. Anyway, the "beta" part will be removed started by next month.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Closing Comment: Double NETStandard1_3 fixed by itself
