### ISSUE TITLE
"The document is too complex to parse"

### ISSUE THREAD

**Issue by pogarek** [zzzprojects/html-agility-pack#241]
Hi

In my .net core project I have the code: 
```
string uri = ""https://www.cinema-city.pl/filmy/303-bitwa-o-anglie";
            HtmlWeb web = new HtmlWeb();
            var htmlDoc = web.Load(uri);
            var n1 = htmlDoc.DocumentNode.SelectSingleNode("//*[@id='more-info']/div/div[2]/div[1]");
```

n1 becomes null. When I try to debug I get : 
```
DepthLevelExceptionMessage [string]:"The document is too complex to parse"
```

How can I overcome this ?

Thank you in advance and best regards

**Comment by JonathanMagnan** [comment]
Hello @pogarek ,

Do you think you could provide a "working" project example/test with this issue? We tried to debug, we get the n1 = null but no debug point with this error was thrown.

It will help my developer investigate the issue more efficiently.

_You can send it to: info@zzzprojects.com if you need to keep the source private_

_We now always ask for a sample project since most issues are either missing some essential information, have some syntax errors or are resolved by the requestor when creating it_

_Having a test project allows us to give faster support and a better experience to users of our free libraries._

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by pogarek** [comment]
Hi @JonathanMagnan 

The source is here  : [https://github.com/pogarek/CinemaCityRatings](url) :-)
n1 and node should not be null. If I do a breakpoint after they are set, I can see not public property : 
```
DepthLevelExceptionMessage [string]:"The document is too complex to parse"
```

Thank you for quick reply
Best regards

**Comment by JonathanMagnan** [comment]
Thank a lot,

My developer will probably check it tomorrow.

Best Regards,

Jonathan

**Comment by pogarek** [comment]
Hi
The xpath path I get from Inspect option in Chrome, when I do it on "Hurricane:Squadron 303 2D" : 
![image](https://user-images.githubusercontent.com/8302383/45405173-1b8bd800-b662-11e8-9c2e-55e06fee741a.png)

There is "more-info" around 10 lines upper. 

HPH
Regards

**Comment by JonathanMagnan** [comment]
Hello @pogarek ,

The additional information is loaded via javascript. The class doesn't exist if you do "view-source", that's one of the reasons why `HAP` return null

You can use the method LoadFromBrowser sometime to handle this kind of situation: http://html-agility-pack.net/from-browser

**Comment by pogarek** [comment]
thank you.
Shold LoadFromBrowser works in .net core ?. Because it seems to be missing in the package HtmlAgilityPack 1.8.7. : 
```
error CS1061: 'HtmlWeb' does not contain a definition for 'LoadFromBrowser' and no extension method 'LoadFromBrowser' accepting a first argument of type 'HtmlWeb' could be found (are you missing a using directive or an assembly reference?)
```
Regards .

**Comment by JonathanMagnan** [comment]
Hello @pogarek ,

Unfortunately no, the `WebBrowser` still doesn't exists in `.NET Core` so we cannot support it yet.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @pogarek ,

This issue will be closed since it has been answered.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
