### ISSUE TITLE
1.8.9htmlnode.selectNodes("//a") selelect a "a" not in this htmlnode

### ISSUE THREAD

**Issue by Iamcaibi** [zzzprojects/html-agility-pack#257]
Version:1.8.9
var node = htmlDocument.SelectSingleNode("//li");
var img = node.SelectSingleNode("//img");
the result img is not in node,it's in the htmldocument;
is this wrong,or my code is wrong?

**Comment by JonathanMagnan** [comment]
Hello @Iamcaibi ,

Do you think you could provide a project sample with this issue?

It will help my developer investigate the issue more efficiently.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by Vita7y** [comment]
I have the same problem if I get HtmlNode from Document and try to find some "//div[0]" in HtmlNode, search always start from the root of Document

**Comment by JonathanMagnan** [comment]
Hello @Vita7y , @Iamcaibi ,

That's how `XPath` work.

- `//`: selects all nodes starting from the root
- `.//`: selects all nodes starting from the current node

There is no so much we can do here ;)

Let me know if that explains correctly the current behavior.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Vita7y , @Iamcaibi ,

This issue will be closed since it has been answered.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Yup, I understand the confusion.

Perhaps we will eventually add an option that will do automatically change `\\` for `.\\` when the select is done from a node.

That "mistake" seems very common.
