### ISSUE TITLE
End tag removed when option tag found in html

### ISSUE THREAD

**Issue by ankit1985** [zzzprojects/html-agility-pack#259]
![image](https://user-images.githubusercontent.com/29271773/47848699-358d9f80-ddf5-11e8-9c2f-005bbadf4818.png)

when i view full html it looks like </option> end tag removed 
![image](https://user-images.githubusercontent.com/29271773/47848764-5bb33f80-ddf5-11e8-9c98-19e28cdae830.png)

currently using HtmlAgilityPack.dll with version 1.8.9.0

**Comment by JonathanMagnan** [comment]
Hello @ankit1985 ,

Do you think you could provide a project sample with this issue?

It will help my developer investigate the issue more efficiently.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by ankit1985** [comment]
As this issue is part to corporate project i will not able provide project here. but i will make another sample project and submit asap. @JonathanMagnan

**Comment by JonathanMagnan** [comment]
Hello @ankit1985 ,

Did you succeed to make your project?

**Comment by JonathanMagnan** [comment]
Hello @ankit1985 ,

This issue will be closed but we will re-open it if you succeed to provide a project.

Best Regards,

Jonathan
