### ISSUE TITLE
Option to use old parsing algorithm

### ISSUE THREAD

**Issue by KristofferK** [zzzprojects/html-agility-pack#275]
I've until now been using version 1.4.9. But as we're moving to asp.net core 2.1, we've to upgrade to a newer version. When we use v1.4.9 on core 2.1, things like "new HtmlWeb().Load(url);" will result in "Cannot access a disposed object.\r\nObject name: 'System.Net.HttpWebResponse'.".

After upgrading to 1.8.14 this problem is gone, and we can use Load(url) again.

We do have a problem though, when we are scraping websites, that contains some invalid html.

One of the sites we're scraping contains the following HTML
https://scontent.faal2-1.fna.fbcdn.net/v/t1.15752-9/50849872_732819520445307_6282651875388948480_n.png?_nc_cat=108&_nc_ht=scontent.faal2-1.fna&oh=0fcf8bf8df6658b825a38249a71b113b&oe=5CBB6C89

They're opening a td tag, but they're closing a th tag.

When parsing this in v1.4.9 I'd get the following html
https://scontent.faal2-1.fna.fbcdn.net/v/t1.15752-9/50699214_359288548184767_5518488506650853376_n.png?_nc_cat=106&_nc_ht=scontent.faal2-1.fna&oh=f514759e19e7546bdde395adfbf46d2b&oe=5CFF7A17

Instead of the two td tags being on same level, it made the latter td tag nested inside the first one. The HTML is now valid.

In the new version (1.8.14) it actually is better at making valid html, I'd say. It changes the </th> to </td>, so they keep being on same level, instead of getting nested.
https://scontent.faal2-1.fna.fbcdn.net/v/t1.15752-9/50827328_311696656124062_4029122925050200064_n.png?_nc_cat=110&_nc_ht=scontent.faal2-1.fna&oh=23be63ae5a86ba63f8fdd837850d29dd&oe=5CF8C9F0

This is great and all. But in my XPaths and regular expressions, they expect the TDs to be nested, but now they aren't. There are lots of scrapers, so I'd prefer not to go through them all and change multiple XPaths where needed. That'd be very time consuming.

Is there anyway we can use v1.8.14, but use the old algorithm from 1.4.9, so we don't have to change all our XPaths and regular expressions, but still be able to use Load(url) from 1.8.14?

**Comment by JonathanMagnan** [comment]
Hello @KristofferK ,

From what I understand your code doesn't work because we have fixed an issue.

Unfortunately, that's not possible to use the old logic ;( You will either need to try an older version that was made before this fix and see if that work or change your `XPATH`.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by KristofferK** [comment]
Hello @JonathanMagnan ,

That's unfortunate. I think I've found a solution that works for me though.

It seems like v1.5.0 works in .net core, but still produces the "wrong" html, that my XPaths are using.

It'd have been great, if I could have used 1.8.14 but still the old logic.

But v1.5.0 seems to do the job for me.

Thanks.

**Comment by JonathanMagnan** [comment]
Hello @KristofferK ,

I will close this one since I don't think it will be ever done to offer something similar to the old logic.
