### ISSUE TITLE
<br> Is ignored/removed in InnerText

### ISSUE THREAD

**Issue by SuuperW** [zzzprojects/html-agility-pack#286]
<br> tags are not replaced with newlines in a node's InnerText property, but are instead simply removed.

string html = "Hello\<br>world.";
HtmlDocument htmlDocument = new HtmlDocument();
htmlDocument.LoadHtml(html);
Console.Write(htmlDocument.DocumentNode.InnerText);

will output:

Helloworld.

**Comment by JonathanMagnan** [comment]
Hello @SuuperW ,

InnerText only keeps text, that's exactly the expected behavior. You will get the same behavior for example with javascript/jquery.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by SuuperW** [comment]
Then, is there any way to get the text of an element as it would show in a browser, without writing my own HTML-parsing code?

**Comment by JonathanMagnan** [comment]
None as I know since you want the "<br>" make a new line but what the "<b>" tag is supposed to do?

You could always make a big find & replace by a new line when a "br" tag is found but that's probably not exactly what you would like it does: https://dotnetfiddle.net/pzemCY
