### ISSUE TITLE
No new data issued

### ISSUE THREAD

**Issue by c0d3ck** [zzzprojects/html-agility-pack#290]
Hello please help me,when I enter the command, everything is fine, but when I enter the command again, the values are no longer parsed from the link, but the old values are used. 

It is necessary for me that at input of a command, the html page was again downloaded and new data was parsed from it.
![465](https://user-images.githubusercontent.com/49695820/56238116-56da0380-6096-11e9-8539-8f9a11d2a621.png)
![5757](https://user-images.githubusercontent.com/49695820/56238117-56da0380-6096-11e9-9ae7-160306d84d4d.png)

**Comment by JonathanMagnan** [comment]
Hello @c0d3ck ,

Can you provide a runnable project/solution or create a Fiddle with this issue? It will help my employe to get started faster to check this issue.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by c0d3ck** [comment]
@JonathanMagnan  
Hello. https://dropmefiles.com/AlqfI

**Comment by JonathanMagnan** [comment]
Hello @c0d3ck ,

Thank for the project, after spending a few hours on it, I don't think we can do anything for it.

`HAP` parse `HTML` but do not manage issue like this one.

We recommend you to try to take the `HTML` via [Selenium](https://www.nuget.org/packages/Selenium.WebDriver/) instead. You will have more chance to make it work since it looks there is some JavaScript involved.

There is not so much we can do on our side beyond that ;(

**Comment by c0d3ck** [comment]
@JonathanMagnan  Hello,thanks,i try
