### ISSUE TITLE
HtmlWeb.GetExtensionForContentType throws an exception on .NET Framework 4.5.2

### ISSUE THREAD

**Issue by alex-jitbit** [zzzprojects/html-agility-pack#294]
### Exception

```
Exception message:

System.MethodAccessException: Attempt by security transparent method 'HtmlAgilityPack.PermissionHelper.GetIsRegistryAvailable()' to access security critical method 'System.AppDomain.get_PermissionSet()' failed.

Assembly 'HtmlAgilityPack, Version=1.11.0.0, Culture=neutral, PublicKeyToken=bd319b19eaf3b43a' is marked with the AllowPartiallyTrustedCallersAttribute, and uses the level 2 security transparency model.  Level 2 transparency causes all methods in AllowPartiallyTrustedCallers assemblies to become security transparent by default, which may be the cause of this exception.
   at HtmlAgilityPack.PermissionHelper.GetIsRegistryAvailable() in C:\Users\Jonathan\source\repos\HtmlAgilityPack\HtmlAgilityPack.Shared\HtmlWeb.cs:line 2570
   at HtmlAgilityPack.HtmlWeb.GetExtensionForContentType(String contentType, String def) in C:\Users\Jonathan\source\repos\HtmlAgilityPack\HtmlAgilityPack.Shared\HtmlWeb.cs:line 993

```

**Comment by JonathanMagnan** [comment]
Hello @alex-jitbit ,

A runnable project/solution or Fiddle is now required if you would like we look at it.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._
_You can send it to: info@zzzprojects.com if you need to keep the source private_
Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by alex-jitbit** [comment]
@JonathanMagnan here's a dotnetfiddle

https://dotnetfiddle.net/qjSYgD

**Comment by JonathanMagnan** [comment]
Hello @alex-jitbit ,

Thank you, my developer looked at it but there is not so much we can do.

This method requires additional permission to check in the key registry available mime type: https://github.com/zzzprojects/html-agility-pack/blob/3a6f0d2173de57650e0fb1c6fda289bf22e53365/src/HtmlAgilityPack.Shared/HtmlWeb.cs#L992-L1017

Honestly, I'm not really sure why it has been done like that as using registry key is mostly always a bad idea for a third party library.

What we could do on our side is doing a try/catch and in the catch using a dictionary of all common mime know mime type.

Is it something that will work for your scenario?

**Comment by alex-jitbit** [comment]
I'm not heavily dependent on this bug, just something I stumbled upon.

You can simply steal code from MS https://github.com/Microsoft/referencesource/blob/master/System.Web/MimeMapping.cs

Or even simply call their method (not sure its good idea since it would add `System.Web` dependency

**Comment by JonathanMagnan** [comment]
Hello @VBWebprofi ,

The v1.11.4 has been released.

Could you try it and let me know if everything is now working as expected?
