### ISSUE TITLE
Feature - Map element

### ISSUE THREAD

**Issue by LukeTOBrien** [zzzprojects/html-agility-pack#300]
Hello there,

I have an existing NodeJS project that is using [jQuery](https://jquery.com/) on the server-side with [jsdom](https://github.com/jsdom/jsdom).  
Basically what I am doing is compiling Markdown and then mapping the elements to my own desired output.

I am now looking at converting the project to .NET Core, I am using [Markdig](https://github.com/lunet-io/markdig) for the Markdown compilation and plan to use HAP to replace jQuery/jsdom.

However one of the function I use the most is the [.map()](https://api.jquery.com/map/#map-callback) function as well as many others.  
Is there currently an equivalent in HAP?  
If I selected all `<div>` elements for eg. could I `foreach` over them and modify each element to a new element?

If this if not possible then I would like to suggest this feature.

**Comment by JonathanMagnan** [comment]
Hello @LukeTOBrien ,

I'm not sure exactly how `map` could be useful in C#.

The following jquery code
```js
$( ":checkbox" )
  .map(function() {
    return this.id;
  })
  .get()
```

Look pretty similar as using a simple `Select` in C#

```csharp
getCheckBox().Select(x => x.id).ToList();
```

I'm failling to see what a `map` function will bring since it seem similar to using `Select`.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by LukeTOBrien** [comment]
Hello,

Yes I see your point... After further working with HAP I can see that I can do all that I need to do.  
I don't think this is needed and I will close the issue.  

Thanks.
