### ISSUE TITLE
HtmlDocument.LoadAsync method

### ISSUE THREAD

**Issue by shravan2x** [zzzprojects/html-agility-pack#313]
### Description
This issue is for a few questions I had about this package:

1. What is the difference between `HtmlDocument.HtmlEncode` and `HtmlEntity.Entitize`?
2. Why is there no corresponding `HtmlDocument.HtmlDecode` function?
3. Given how common this workflow is:
```
HtmlDocument dom = new HtmlDocument();
dom.Load(someStream);
```
, wouldn't it make sense to include constructors (or static initializers) to do this in one line like
```
HtmlDocument dom = new HtmlDocument(someStream);
```
4. Why is there no `LoadAsync(someStream)` method on `HtmlDocument`? Wouldn't this avoid blocking threads when reading from slower streams?

### Further technical details
- HAP version: `1.11.8`
- NET version (net472, netcore, etc.): `netstandard2.0`

**Comment by JonathanMagnan** [comment]
Hello @shravan2x ,

Let start by saying that we are not the creator of HAP, we support it since 2 years ago so we are not aware of some initial decision.

> What is the difference between HtmlDocument.HtmlEncode and HtmlEntity.Entitize?

HtmlEncode: encode character to escape in XML `&, <, >, ', "`

Entitize: clone a node and entitize it: https://github.com/zzzprojects/html-agility-pack/blob/1dfe439abf70518690106ac497455948d9c73390/src/HtmlAgilityPack.Shared/HtmlEntity.cs#L768

Beside being able to use eithe the code or the name, I'm not sure why a similar logic to `HtmlEncode` has not been used.

> Why is there no corresponding HtmlDocument.HtmlDecode function?

Because it never has been required I guess

> HtmlDocument dom = new HtmlDocument(someStream);

This is probably the way I would have done it. However, there are currently thousands of examples in some book or tutorial that currently use the `Load` method. So I don't think it worth to add a constructor and might confuse some people.

> Why is there no LoadAsync(someStream) method on HtmlDocument
Probably because that has never been asked. This library has been created in `2004` and async was not existing at this time. So since no one have asked, this method has never been added.

We hope to be able to create a v2.x one day but it requires several hundreds of hours. Time is hard to find for a free librairies ;(

**Comment by shravan2x** [comment]
That really clears things up, thanks.
