### ISSUE TITLE
Bad parse error returned with invalid tag nesting

### ISSUE THREAD

**Issue by masonwheeler** [zzzprojects/html-agility-pack#354]
### Description
When parsing the following HTML, `<p><h1>invalid nesting</h1></p>` the `ParseErrors` property creates an incorrect error: "Start tag `<p>` was not found", with the position being the position of the `</p>` tag.

This makes it appear that there is a syntactical problem with the HTML that was provided.  This is quite obviously not the case; the start P tag is right there, plainly visible at the start of the HTML!  The actual problem is a *semantic* problem: it's not valid to nest a H1 tag inside a P tag.

The error returned should accurately reflect the real problem, rather than providing the confusing nonsense seen in the current version.

### Fiddle or Project
https://dotnetfiddle.net/Eo1bGv

### Further technical details
- HAP version: 1.11.17
- NET version: .NET Framework 4.8

**Comment by JonathanMagnan** [comment]
An "h1" tag cannot be nested in a "p" tag.

If you actually open your code in a browser and check the source code, you will find that the first `p` is closed and a new `p` is opened.

```csharp
<body data-gr-c-s-loaded="true">
		<p></p><h1>bad nesting</h1><p></p>
	
</body>
```

I guess that's why `HAP` throw an error since your second `p` tag (the closed one) doesn't have a corresponding open `p` tag.

Let me know if that explains correctly the current behavior.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by masonwheeler** [comment]
> An "h1" tag cannot be nested in a "p" tag.

Yes, that's what I said in my error report: it's not valid to nest a H1 tag inside a P tag.

> If you actually open your code in a browser and check the source code, you will find that the first `p` is closed and a new `p` is opened.

```
<body data-gr-c-s-loaded="true">
		<p></p><h1>bad nesting</h1><p></p>	
</body>
```

Yeah.  And if I plug *that* into HAP, there isn't an error, because there's no P closing tag without a matching P opening tag.  So this does not adequately explain the current behavior.

The current behavior is that HAP reports I have a closing P tag without an opening P tag.  This is not true, and it remains untrue even when automatic DOM-repairing actions are taken to munge it into valid HTML.  The actual error that should be reported is that it's not valid to nest a H1 tag inside a P tag.  The current error is factually incorrect and nonsensical.

**Comment by JonathanMagnan** [comment]
Your syntax is valid.

A `<p>` tag doesn't necessarily need a closing tag. It's implicitly added.

> A p element's end tag can be omitted if the p element is immediately followed by an address, article, aside, blockquote, details, div, dl, fieldset, figcaption, figure, footer, form, h1, h2, h3, h4, h5, h6, header, hgroup, hr, main, menu, nav, ol, p, pre, section, table, or ul element, or if there is no more content in the parent element and the parent element is an HTML element that is not an a, audio, del, ins, map, noscript, or video element, or an autonomous custom element.
https://html.spec.whatwg.org/#the-p-element
