### ISSUE TITLE
Error response causes a memory leak in Visual studio

### ISSUE THREAD

**Issue by loganwol** [zzzprojects/html-agility-pack#361]
Hi, 

I'm using HAP to validate (in unit test) the HTML content I'm generating from a tool. I'm using FluentAssertions to Assert the tests and when an Assert is triggered example htmlElement.Attribute["rowspan"].Should().BeNull() and it's not, the resulting error outputs the full HTML. Looking at the error (click on the failure icon on the test) in the test result popup causes Visual Studio to hang and never recover. Looking at VS instance in Task Manager, I see a a memory leak in VS.

Regards

**Comment by JonathanMagnan** [comment]
Hello @LoganHollins ,

Do you think you could provide a project sample with this issue?

It will help my developer investigate the issue more efficiently.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by LoganHollinsAH** [comment]
I think you meant to tag @loganwol @JonathanMagnan.

**Comment by JonathanMagnan** [comment]
Obviously ;)
