### ISSUE TITLE
xpath string() error

### ISSUE THREAD

**Issue by yedajiang44** [zzzprojects/html-agility-pack#371]
xpath code
```
string(.)
```
error
```
Expression must evaluate to a node-set.
```

**Comment by JonathanMagnan** [comment]
Hello @yedajiang44 ,

Do you think you could provide a project sample with this issue?

It will help my developer investigate the issue more efficiently.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by yedajiang44** [comment]
@JonathanMagnan the demo code [https://dotnetfiddle.net/uayGG0](https://dotnetfiddle.net/uayGG0)

**Comment by JonathanMagnan** [comment]
Hello,

Here is a post that explains why it doesn't work and how to make it work with the navigator: https://stackoverflow.com/a/17840143/5619143

Here is an online example: https://dotnetfiddle.net/SBHxEo

Let me know if that solves your question ;)

**Comment by yedajiang44** [comment]
@JonathanMagnan Thanks!This is what i want!
