### ISSUE TITLE
Entire URL website is not pulling in all html tags

### ISSUE THREAD

**Issue by ttaylor29** [zzzprojects/html-agility-pack#380]
I have some div tags that are not within the html once I read it in to HTML Agility.

Why would some div tags be left out?

=============

I am trying to get a div that has no attributes or classes
I'm tried a number of items but it can't seem to find anything under a specific div tag that has no attributes.
If a div tag has no attributes and just is there a way to get it via html agility?
https://imgur.com/a/HVEpOo8
===============

**Comment by JonathanMagnan** [comment]
Hello @ttaylor29 ,

Do you think you could provide a project sample with this issue?

It will help my developer investigate the issue more efficiently.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by ttaylor29** [comment]
Yes, let me do that.

**Comment by ttaylor29** [comment]
I sent you all an email!

**Comment by JonathanMagnan** [comment]
Awesome @ttaylor29, 

we will take a look at it and get back to you via email! 

best regards, 

Jon

**Comment by JonathanMagnan** [comment]
Hello @ttaylor29 ,

You are currently looking for the `LoadFromBrowser` I believe.

```csharp
string url = "[website_ur]";
var web1 = new HtmlWeb();

var doc1 = web1.LoadFromBrowser(url, s =>
{
    var found = s.Contains("wisss_gameHover");

    if (found)
    {

    }

    return found;
});

var s2 = doc1.DocumentNode.InnerHtml;
var scoreRows = doc1.DocumentNode.SelectNodes("//div[@class='wisss_gameHover']").ToList();
```

The current code will use the `WebBrowser` and wait until the class `wisss_gameHover` is loaded before continuing in the code.

**Comment by ttaylor29** [comment]
YESSSSSSSSSSSSSS!!! 

Let me try this later today (hopefully) and I'll report back to you all.

Thanks a bunch! :-)

**Comment by JonathanMagnan** [comment]
awesome!

we will be looking forward to hearing from you ;)

**Comment by ttaylor29** [comment]
:-)

Sorry I didn't get to test it as I need to check it while the code is being injected in. It usually happens during the day right now. I'll try again tomorrow.

**Comment by ttaylor29** [comment]
THIS WORKED!!!!!!!!

Thanks a lot for looking at my issue for me!

`            var web1 = new HtmlWeb();

            var doc1 = web1.LoadFromBrowser(url, s =>
            {
                var found = s.Contains("wisbb_inningAndOuts");

                if (found)
                {

                }

                return found;
            });

            var s2 = doc1.DocumentNode.InnerHtml;
            var scoreRows = doc1.DocumentNode.SelectNodes("//div[@class='wisbb_inningAndOuts']").ToList();`
