### ISSUE TITLE
StackOverflowException when retrieving document node on UWP platform

### ISSUE THREAD

**Issue by ooikengsiang** [zzzprojects/html-agility-pack#382]
### Description
StackOverflowException when retrieving document node on UWP platform. This happen after nuget version 1.11.19. This has no effect on Xamarin Android / iOS that running the same piece of code.

### Exception
Since the stack is overflowed, no stack trace is available.

### Fiddle or Project
var doc = new HtmlDocument();
doc.LoadHtml(respondContent);
var productInfoNode = doc.DocumentNode.Descendants("div").FirstOrDefault(x => x.GetAttributeValue("class", null)?.Contains("product-info") ?? false);
if (productInfoNode != null) // crash
{
}

### Further technical details
Nuget version 1.11.18 running perfectly fine on UWP.
Nuget version 1.11.22 have the same problem too.

**Comment by JonathanMagnan** [comment]
Hello @Jon,

Do you think you could provide a project sample with this issue?

It will help my developer investigate the issue more efficiently.

At this moment, I don't; think we can do anything with this request unless we have the content of `respondContent` to reproduce the issue

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by ooikengsiang** [comment]
@JonathanMagnan Here is the sample project: [https://github.com/ooikengsiang/HtmlAgilityPackStackOverflow](https://github.com/ooikengsiang/HtmlAgilityPackStackOverflow)

**Comment by mrjfalk** [comment]
I've also ran into StackOverflow issues in 1.11.22, but after reading this post I downgraded to 1.11.18 and it all works fine again. Unfortunatly I don't have a simple reproducable project at the moment.

**Comment by JonathanMagnan** [comment]
Hello @ooikengsiang , @mrjfalk ,

The v1.11.23 has been released.

This new version should fix the issue with the method `GetAttributeValue` that causes this StackOverflow Exception.

Let me know if everything works as expected with the latest version.

**Comment by ooikengsiang** [comment]
@JonathanMagnan v1.11.23 working as intended.
Thank you so much for the quick fix and update.

**Comment by mrjfalk** [comment]
Thanks, fixed the bug for me as well :)
