### ISSUE TITLE
[Bug] OuterLength throws NullReferenceException if HtmlDocument not loaded

### ISSUE THREAD

**Issue by artemious7** [zzzprojects/html-agility-pack#391]
```
var doc = new HtmlDocument();
var length = doc.DocumentNode.OuterLength; // throws NullReferenceException, because OuterHtml is null
```

If a library throws NullReferenceException, it's almost always a bug, so it must be fixed

https://github.com/zzzprojects/html-agility-pack/blob/b360bf4634f2a3ac304384bbd0a25214a00a5015/src/HtmlAgilityPack.Shared/HtmlNode.cs#L574

**Comment by JonathanMagnan** [comment]
Hello @artemious7 ,

I don't think we will change this behavior for backward compatibility.

If nothing is loaded, I don't mind really it throw null. Otherwise, we will have like 50 properties to modify and we could break some developer code which will not be really better.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by artemious7** [comment]
Do you mean someone may expect NullReferenceException and if it doesn't throw, it will break their code? Ok, I understand
