### ISSUE TITLE
'DocumentNode.InnerHtml' threw an exception of type 'System.NullReferenceException'

### ISSUE THREAD

**Issue by TTDN** [zzzprojects/html-agility-pack#4]
Hi, i'm new in html agility pack.

I want to get data from a real estate website, but when i load(url), i have a error:

![image](https://cloud.githubusercontent.com/assets/8373057/26304028/07ab4562-3f14-11e7-9fb2-d276b926b84f.png)

Here is my code:
HtmlWeb web = new HtmlWeb();

HtmlAgilityPack.HtmlDocument documentx = web.Load(url);

Here is url i want to load: "http://batdongsan.com.vn/cho-thue-nha-tro-phong-tro-duong-ba-le-chan-phuong-tan-dinh-2/ngay-gan-tran-quang-khai-quan-1-pr12422590"

Can you help me? Sorry for my bad english. :(

**Comment by JonathanMagnan** [comment]
Hello @TTDN ,

This issue happen because the page has no content type. So by default, it's currently not considered an HTML page, so not parsed.

We are currently looking to verify the impact of changing this default behavior to enable the HTML parse when the content type is null or empty.

A fix should be available in a few hours.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @TTDN ,

The v1.5.0-beta4 has been released:
https://www.nuget.org/packages/HtmlAgilityPack/1.5.0-beta4

By default, when the content type is null or empty, HAP now try to load a first time the content as if it was HTML.

Let me know if that fixed your issue.

Best Regards,

Jonathan

**Comment by TTDN** [comment]
Hello @JonathanMagnan ,

I have a new issue when i update to 1.5.0-beta4. :(
![image](https://cloud.githubusercontent.com/assets/8373057/26334487/93952d4c-3f8f-11e7-8e26-6280f3f8ab61.png)
This issue is before NullReferenceException, so i can't continue.

When i search this issue on google, i got a link: https://stackoverflow.com/questions/38182384/htmlagilitypack-queryselectorall-throwing-exception-potentially-fizzler-dll-ver

What should i do?

**Comment by JonathanMagnan** [comment]
Hello @TTDN ,

Thank you for reporting.

This issue happen because the the old signature 
`public IEnumerable<HtmlNode> Descendants()`

has been replaced by a method with a default value 
`public IEnumerable<HtmlNode> Descendants(int level=0)`

The fix on our side is very simple: Simply also adding the method without overload. We already tested it and it seems to work.

A new version will be available in a few hours,

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @TTDN ,

The v1.5.0-beta5 has been released:
https://www.nuget.org/packages/HtmlAgilityPack/1.5.0-beta5

We added the method has specified which should fix this issue.

Let me know if that fixed your issue.

Best Regards,

Jonathan

**Comment by TTDN** [comment]
It working!!!

Thank you so much @JonathanMagnan . 💃

**Comment by abhishekvats** [comment]
![image](https://user-images.githubusercontent.com/5195111/38403690-22fca26a-391a-11e8-95cb-a3b5d9deaded.png)

**Comment by zubairfarooq13** [comment]
Hi, i am new in HtmlAgility. i am working on it. i have face this System.exception and null exception.
Please help me
Thanks
![vs_error](https://user-images.githubusercontent.com/43909324/46572127-9b415580-c935-11e8-9b95-7e659337b65d.png)

**Comment by JonathanMagnan** [comment]
Hello @zubairfarooq13 ,

If you want some help, please open a new Issues and provide us a project sample that reproduces this issue.

Best Regards,

Jonathan

**Comment by zubairfarooq13** [comment]
now solved this issue.

Thanks
________________________________
