### ISSUE TITLE
Retrive center child from footer node

### ISSUE THREAD

**Issue by RuggeriLuca** [zzzprojects/html-agility-pack#403]
I try to retrieve all child note from the node but it's retrieve count 0 
here an example of the html code : 

```
<area name="Footer" parentName="currentDraw">
   <line x1=12 y1=5 x2=600 y2=5 penWidth=2>
   <o y=5><center>ΤΥΠΩΘΗΚΕ 28/07/2020 10:36:25</center></o>
   <center>ΠΡΑΚΤΟΡΕΙΟ: 234022-234022002 23402282</center>
   <center>ΚΩΔ. ΣΥΝ.:cb3fba</center>
   <center>ΚΩΔ. ΔΕΛΤΙΟΥ.:100003627571</center>
   <center><barcode format=graphics type=PDF value="292357408800000058881443144488010000008723000000974152808"></barcode></center>
 </area> 


```
what i was tried to do is retrieve all center child of the area node but when i count it = 0 
```

strname = doc.DocumentNode.SelectSingleNode("//area[@name='Footer']")
        	
        	debugLogJsonFormat(strname.OuterHtml())
        	
        	debugLogJsonFormat(strname.ChildNodes.Count())

```

**Comment by JonathanMagnan** [comment]
Hello @RuggeriLuca ,

Unfortunately, the `<area>` tag has his own rules.

This is an empty element that is not expected to contains some tags.

You can bypass this rule by removing it from the list (so it will work like `div` for example)

```csharp
// DO IT only once
HtmlNode.ElementsFlags.Remove("area");

var htmlDoc = new HtmlDocument();
htmlDoc.LoadHtml(html);

var strname = htmlDoc.DocumentNode.SelectSingleNode("//area[@name='Footer']");
```

but by default, you are currently getting the expected behavior for this element tag

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
