### ISSUE TITLE
Adds ="" to href tag 

### ISSUE THREAD

**Issue by cskanan** [zzzprojects/html-agility-pack#404]
### Description
Adds ="" to href tag when you load HTML document in C#

See this line in the output. 
<a class="g-bg-red g-font-size-16 g-color-white u-pagination-v1__item g-rounded-15 g-font-weight-500 ReadMore" href="@Url.Action(" latest_news","home")#article9e"**=""**>Read More</a>

Please advice me if you need more details

### Exception
No Exception

Exception message:
No stack trace

### Fiddle or Project
please see the attached aviewpage.cshtml

After the above HTML loaded using 
HtmlDocument htmlDoc = new HtmlDocument();
htmlDoc.Load(aviewpage); // need to be correct file path

//The output  is 

Please see attached output.cshtml
[HtmlLoad.zip](https://github.com/zzzprojects/html-agility-pack/files/5054862/HtmlLoad.zip)

### Further technical details
ASP.NET Core,
C#,
VS2019,
Razor page,
HtmlAgilityPack 1.11.24

**Comment by JonathanMagnan** [comment]
Hello @cskanan ,

HAP is an HTML parser. You currently have some code which contains server code: `"@Url.Action("news","home")#article9e"`

We will look at it since we `lightly` support server code but I cannot guarantee anything will be done here.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @cskanan ,

We took some time on this request last week but unfortunately, we choose to not support it as this request open too many cases in which some different parsing/logic is required to handle most of them.

As said, HAP is an HTML parser and not a razor parser, so we expect to parse the final HTML code
