### ISSUE TITLE
ParseErrors but correct html file

### ISSUE THREAD

**Issue by DavidMakerson** [zzzprojects/html-agility-pack#405]
Hi,

I wanted to load an html file and delete all attributes included in the html tags.
Now I get the problem that, when i load the string i get some parsing errors and lose some html endtags.

HTML Filetext:
"<p class="MsoNormal"><ul><li>Schnell  blutstoppend!</li></ul></p>   <p class="MsoNormal">Stoppt  schnell und wirksam kapillare (oberflächliche) Blutungen. Bereits nach wenigen  Minuten ist die Blutung vollständig gestoppt. </p>    <p class="MsoNormal"><ul><li>Kein  erneutes Bluten bei Entfernen!</li></ul></p>"

Code:
var htmlDocument = new HtmlAgilityPack.HtmlDocument();
htmlDocument.OptionAutoCloseOnEnd = true;
htmlDocument.OptionCheckSyntax = false;
htmlDocument.OptionFixNestedTags = true;
htmlDocument.OptionAutoCloseOnEnd = true;
htmlDocument.OptionWriteEmptyNodes = true;

htmlDocument.LoadHtml( HTML-File-from-above );

foreach (var eachNode in htmlDocument.DocumentNode.Descendants().Where(x => x.NodeType == HtmlNodeType.Element))
{
eachNode.Attributes.RemoveAll();
}
return htmlDocument.DocumentNode.OuterHtml;

In my result string i lose all </p> tags after the enumeration, with parse error text = "TagNotOpened"?

**Comment by DavidMakerson** [comment]
here's the file
`<p class="MsoNormal"><ul><li>Schnell  blutstoppend!</li></ul></p>    <p class="MsoNormal">Stoppt  schnell und wirksam kapillare (oberflächliche) Blutungen. Bereits nach wenigen  Minuten ist die Blutung vollständig gestoppt. </p>    <p class="MsoNormal"><ul><li>Kein  erneutes Bluten bei Entfernen!</li></ul></p>`

**Comment by JonathanMagnan** [comment]
Hello @DavidMakerson ,

An `<ul>` cannot be inside `<p>`. So the library skip your closing `</p>` since it's not in the right place.

Let me know if that explains correctly the current behavior.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
