### ISSUE TITLE
There is no parse error if the tag is unclosed.

### ISSUE THREAD

**Issue by foman** [zzzprojects/html-agility-pack#411]
### Description
`<html><body>aa</body></html` 
The end html tag is not closed. but it doesn't report any parse error, is this by design?

### Further technical details
- HAP version:
- NET version (netcore):

**Comment by JonathanMagnan** [comment]
Hello @foman ,

Unfortunately, the `ParseErrors` is not 100% accurate.

A lot of change has been made to automatically fix some HTML and no parsing errors are longer returned for them. There is no plan to fix it at this moment since this would probably require to re-write too much code to make sure all errors is returned correctly.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
