### ISSUE TITLE
HtmlNode.InternalInnerText should have a level parameter passed in to it

### ISSUE THREAD

**Issue by devanshu0987** [zzzprojects/html-agility-pack#413]
### Description
We are experiencing that in some conditions, the InnerText leads to StackOverflow when the HTML has high depth.
For ex: http://barntheatreoxted.co.uk/calendar.html
Problem is, we are not able to reliably repro the StackOverflow on our local machines.

Every recursion should have a control parameter.
In this function, we keep on recusing for the whole DOM tree without any check on the depth of the recursion.
Following is the code piece which is potentially causing the issue. If you notice, we just want to check on if nodes are not empty. But for this, we basically recurse for a lot of nodes which is wasteful.

```
var tdNodes = node.SelectNodes(".//td")?
                .Where(x => !String.IsNullOrWhiteSpace(x.InnerText))
                .ToList();
```
### Exception
StackOverflow exception

```
Exception message:
Stack trace:
```

### Fiddle or Project
Not able to repro it reliably.
I understand that it would be hard for you to take this seriously since I am not able to provide you with a repro example.

### Further technical details
- HAP version: 1.11.24
- NET version (net472, netcore, etc.): .NET 4.5.2

**Comment by JonathanMagnan** [comment]
Hello @devanshu0987 ,

If you look at their HTML, it's heavily broken:

```html
<i><font size="-2" face="Arial, Helvetica, sans-serif"><b><i><font face="Arial, Helvetica, sans-serif" size="1">
<i><font size="-2" face="Arial, Helvetica, sans-serif"><b><i><font size="-2"><i><font size="-2" face="Arial, Helvetica, sans-serif">
<b><i><font size="-2"><i><font size="-2" face="Arial, Helvetica, sans-serif"><b></b></font></i></font></i></b></font></i></font></i>
</b></font></i></font></i></b></font></i></b></font></i></font></i></b></font></i></font></i></b></font></i></font></i></b></font>
</i></b></font></i></font></i></b></font></i></font></i></b></font></i></font></i></b></font></i></b></font></i></font></i></b></font>
</i></font></i></b></font></i></font></i></b></font></i></b></font></i></font></font></i></font></i></b></font></i></font></i></b>
```

And it continues like this for way more times. So obviously this leads to some Stack Overflow since it reaches the maximum limit of recursion.

However, since a `Stack Overflow` exception is thrown, this is impossible for you to catch it which don't make it very useful.

The v1.11.26 has been released, in this version, we added the support for `MaxDepthLevel` for the `InnerText`. So while it throws an error (was options was already existing and throwing an error was the current behavior), you can now at least handle it.

For example:

```csharp
HtmlDocument.MaxDepthLevel = 2000;

var web = new HtmlWeb();
var doc = web.LoadFromBrowser("http://barntheatreoxted.co.uk/calendar.html");

var nodes = doc.DocumentNode.SelectNodes(".//td")?.IsNotNullOrEmptySafe();
				
public static class CustomExtensions
{
	public static List<HtmlNode> IsNotNullOrEmptySafe(this HtmlNodeCollection nodes)
	{
		var result = new List<HtmlNode>();

		if (nodes != null)
		{
			foreach (var node in nodes)
			{
				try
				{
					if (!string.IsNullOrEmpty(node.OuterHtml))
					{
						result.Add(node);
					}
				}
				catch (Exception e)
				{
					// happen when maximum level is reached, you could check for the message if you wish
				}
			}
		}

		return result;
	}
}
```

I asked my developer to add support to the `MaxDepthLevel` pretty much everywhere he believe we should add it.

Let me know if the current fix covers your scenario.

Best Regards,

Jon

**Comment by devanshu0987** [comment]
Hi @JonathanMagnan , thanks a lot. Yes, this solves the problem for us. We will consume the latest version right away. You can close the issue.
