### ISSUE TITLE
i just want to delete all img in the head but why it delelted all img in the HtmlDocument

### ISSUE THREAD

**Issue by AtlantisDe** [zzzprojects/html-agility-pack#414]
### Description
i just want to delete all img  in the  
```html
<head> </head>
```
but why 
it  delelted all img  in  HtmlDocument

Crying, the html of the entire hundreds of thousands of webpages is scrapped and cannot be restored. The pictures are gone.

### Code
 

```c#
 var head = doc.DocumentNode.Element("html")?.Element("head");
            if (head.IsNullOrEmpty() == true)
            {
                return null;
            }

            var imgItems = head.SelectNodes("//img");

            if (imgItems.IsNullOrEmpty() == false)
            {
                foreach (var item in imgItems)
                {
                    item.Remove();
                }
}
```

**Comment by zgabi** [comment]
This is how SelectNodes works... this is not a HtmlAgilityPack featue.

Just check this sample code: https://dotnetfiddle.net/3spoT5

I'm sorry that you lost your data, but I suggest you to test every time your code before you run it on live/important data which has no backup.

**Comment by JonathanMagnan** [comment]
Hello @AtlantisDe ,

When you have already selected a node, you must use `head.SelectNodes(".//img");` (see the added "."), to tell the new search should start from the current node.

To make it clear, when a node is already selected:
- `//`: Select from the document root
- `.//`: Select from the current node

As @zgabi  said, that's how `XPath` work so that's not a bug.

Always have a backup when you make this kind of changes, I believe this is something you will never ever forget again.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by AtlantisDe** [comment]
OK thank u very much.. 
@JonathanMagnan
