### ISSUE TITLE
SelectNodes returns 'null' on valid XPath

### ISSUE THREAD

**Issue by WrongBit** [zzzprojects/html-agility-pack#421]
I have xml-like doc:

    <FBResponse>
      <GetGalsResponse>
        <Gal id="...">
        ...
        </Gal>
        <Gal id="...">
        ...
        </Gal>
      </GetGalsResponse>
    </FBResponse>

I load it in HtmlDocument (and in debug mode I made sure I have full hierarchy). Then I try to select 'Gal' nodes:

    var res = doc.DocumentNode.SelectNodes(@"//Gal");

As you see, it's elementary, valid XPath. But instead of array of 'Gal' nodes I just get `null`. Why even such simple code doesn't work?

**Comment by JonathanMagnan** [comment]
Hello @WrongBit ,

You need to specify the tag in lowercase

```csharp
var res = doc.DocumentNode.SelectNodes(@"//gal");
```

Best Regards,

Jon

**Comment by WrongBit** [comment]
@JonathanMagnan : thanks, it works! But why it implemented like this? It's not even "case-insensitive", it's lowercased!! Why not "camel-cased"? hex-encoded? I didn't expect such crazy solution for such popular library!

**Comment by JonathanMagnan** [comment]
I guess this is for having the same behavior as all major browsers.

When you take the `xpath` from their developer tools, the `xpath` is all in lower case.

In fact, even all elements are in lowercase when you inspect it.

It might be another reason since I'm not the original author of this library.

**Comment by WrongBit** [comment]
@JonathanMagnan : thanks for idea. But IMHO there is no any correlation betwen how browser works and usage of the library in absolutely different platform! Moreover: case can be important and developer has no right to hardcode "everything is lowercase".

The one thing he could do is total case insensitivity, meaning with pattern "//AbC" I can find <abc>, <aBc>, etc. Nothing done like this. :((

**Comment by JonathanMagnan** [comment]
Unfortunately, my developer tried but didn't find a quick way to make it happens.

If you wish, the project is open source so you can always look and provide us a pull if you find how to do it (we will need an option here to enable it as it cannot be the default behavior due to backward compatibility).

Best Regards,

Jon
