### ISSUE TITLE
node.OuterHtml Lose img element "/"

### ISSUE THREAD

**Issue by yuejunhi** [zzzprojects/html-agility-pack#425]
## 1. Description
Create img HtmlNode
HtmlNode node = HtmlNode.CreateNode("<img src=\"123.jpg\"/>");
Get the html string from the created node object：node.OuterHtml is equal "<img src=\"123.jpg\">"， lose “/”.
How to get complete html string "<img src=\"123.jpg\"/>"?

**Comment by JonathanMagnan** [comment]
Hello @yuejunhi ,

This is by purpose since closing is invalid in `HTML 5`. See the following answer: https://stackoverflow.com/a/54412209

If you wish, we could check if that's possible to add an option to force the "close" which I believe will make sense for many people.

Just let us know if you need this option or not.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by yuejunhi** [comment]
Hello @JonathanMagnan ,

If you can add an option to force the "close",please  like "<img src='' />".

Best Regards,

yue

**Comment by JonathanMagnan** [comment]
Sure, we will look at it

**Comment by JonathanMagnan** [comment]
Hello @yuejunhi ,

Look like we already have this options. See the following example:

```csharp
HtmlDocument htmlDocument = new HtmlDocument();
htmlDocument.OptionWriteEmptyNodes = true;
htmlDocument.LoadHtml(@"<div><img src=""123.jpg"" />");
var test = htmlDocument.DocumentNode.OuterHtml;
```

Let me know if that's what you were looking for.

Best Regards,

Jon

**Comment by yuejunhi** [comment]
Hello @JonathanMagnan ,

Could you override the method of “HtmlNode.CreateNode(string html)” ，like HtmlNode.CreateNode(string html, bool OptionWriteEmptyNodes)“”？
Let me set htmlDocument.OptionWriteEmpty value equal true or false！

Best Regards,

Yue

**Comment by JonathanMagnan** [comment]
Oh I see,

I copied the code from my developer but that doesn't fit 100% for your requirement.

Sure, we will look at it.

**Comment by yuejunhi** [comment]
Hello @JonathanMagnan ,

Please see the following example:
HtmlNode node = HtmlNode.CreateNode("<img src=\"123.jpg\" />");
string htmlStr = node.OuterHtml;
The result "htmlStr",we want , is equal "<img src=\"123.jpg\"/>",
but we get "<img src=\"123.jpg\">" ,lose "/";
Could you override the method of “HtmlNode.CreateNode(string html)” ，like "HtmlNode.CreateNode(string html, bool OptionWriteEmptyNodes)”？
Let me set htmlDocument.OptionWriteEmpty value equal true or false！
Best Regards,

Yue

**Comment by JonathanMagnan** [comment]
Hello @yuejunhi ,

The v1.11.31 has been released.

It's now possible to pass a builder to choose some options such as `OptionWriteEmptyNodes`

Here is an example:

```csharp
HtmlNode node2 = HtmlNode.CreateNode(@"<img src=""123.jpg"" />", options => options.OptionWriteEmptyNodes = true);
```

Let me know if you successfully implemented the solution.

Best Regards,

Jon
