### ISSUE TITLE
Feature: Would be nice to have a way of preserving empty attributes

### ISSUE THREAD

**Issue by POFerro** [zzzprojects/html-agility-pack#446]
Hi,

With current available options an html document read with hap and written back has all empty attributes written with empty string.
This is quite annoying for cases like `<input required />` or angular directives like `<button mat-button></button>`.

Would be nice to have an option in document to preserve these empty attributes and write them the same way as read.
This property of attribute would of course be set to false if the attribute gets a value set :).

Thanks
POFerro

**Comment by JonathanMagnan** [comment]
Hello @POFerro ,

As said in your pull request, it has been refused since that was already possible (had a bug) with the following option:

```csharp
d.GlobalAttributeValueQuote = AttributeValueQuote.Initial;
```

Which keeps the original quote value (double quote, single quote, no quote, and now no value).

Let me know if that was exactly what you were looking for.

Best Regards,

Jon

**Comment by POFerro** [comment]
Thanks @JonathanMagnan , everything works like a charm.
Thanks for the mention in the release I was flattered :).
