### ISSUE TITLE
SelectNodes doesn't find some nodes by XPath

### ISSUE THREAD

**Issue by synapsechain** [zzzprojects/html-agility-pack#485]
## 1. Description
HAP doesn't find some nodes

## 2. Exception
No exception

## 3. Fiddle or Project
Fiddle: https://dotnetfiddle.net/BbdvBN

## 4. Any further technical details
- HAP version: 1.11.45
- NET version: net6.0

**Comment by JonathanMagnan** [comment]
Hello @synapsechain ,

Thank you for reporting, I can confirm that I get the same issue and have no problem retrieving some other elements by class name on this page.

We will investigate it.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/)

**Comment by JonathanMagnan** [comment]
Hello @synapsechain ,

If you look the source code, you will see that the `a` element is in a script tag. This means this is considered as a `script` (used for creating template).

I believe you want the `HTML` once it is loaded. Since you use .NET6.0, we recommend `selenium` to grab to interact with HTML  ([tutorial](https://riptutorial.com/selenium-webdriver/learn/100000/overview)) as our library only parse the source html

Best Regards,

Jon

**Comment by synapsechain** [comment]
Thank you, Jon
