### ISSUE TITLE
Unable to parse XML CDATA

### ISSUE THREAD

**Issue by melinyi** [zzzprojects/html-agility-pack#495]
XML：
`<a><![CDATA[ content123123 ]]><a/>`

HtmlAgilityPack Parse：
`InnerText = "";`
`InnerHtml = "<![CDATA[ content123123 ]]>"`

What I need：
InnerText = "content123123 ";

**Comment by elgonzo** [comment]
HtmlAgilityPack (HAP) is a **HT**ML parser. And according to the HTML standard, CDATA sections in HTML outside "foreign content" are to be treated like comments (https://html.spec.whatwg.org/multipage/parsing.html#parse-errors):

> **cdata-in-html-content** | This error occurs if the parser encounters a CDATA section outside of foreign content (SVG or MathML). The parser treats such CDATA sections (including leading "[CDATA[" and trailing "]]" strings) as comments.

So it makes sense that CDATA content is not part of the _innerText_, because according to the HTML standard it should be treated as comments. Which HAP does; it turns such CDATA sections into comment nodes.

Note that according to the HTML standard, such comments should not only contain the pure CDATA content like "content123123", but should also include the leading and trailing "_[CDATA[_" and trailing "_]]_". However, here HAP diverges a bit, also additionally including the "_\<!_" and "_\>_", which is not mandated by the HTML standard.

Comment nodes in HAP are represented by `HtmlCommentNode` instances, which include both ordinary HTML comments `<!-- ... -->` as well as comments born from CDATA sections. The _NodeType_ property of  _HtmlCommentNode_ instances is `HtmlNodeType.Comment`.
 
So, one possible approach to get the CDATA section content could be as follows:

1. Query the document or element(s) of interest for child/descendant/sibling comment nodes.
2. Apply a regex pattern match to the content of the found comment nodes to (A) test whether they are CDATA sections and (B) extract the actual content of the CDATA section comment. Perhaps HAP offers some utility function to simplify this step, but i am not aware of any such function.

(Dotnetfiddle demo illustrating this approach: https://dotnetfiddle.net/csuiyB)
