### ISSUE TITLE
Licensing query

### ISSUE THREAD

**Issue by craigfowler** [zzzprojects/html-agility-pack#5]
This fork of the HAP has a license file indicating that it is dual-licensed under the MIT license and a proprietary license.

Previously, the HAP was licensed under the MS-PL. Clause 3D of the MS-PL states that you may only distribute the source code under that same license.

Do you have the permission of all of the previous contributors to re-license their work & submissions? Otherwise this library may be a little dangerous to use, as it could be threatened by copyright takedown notice.

Source: https://htmlagilitypack.codeplex.com/license

**Comment by JonathanMagnan** [comment]
Hello @craigfowler ,

That's not a fork, that's now the new official repository of this library.

To make it short, I'm not the original author. But I purchased the ownership, trademark, copyright and anything else related to this product from the author since this library was not longer supported.

Let me know if you have more question ;)

Best Regards,

Jonathan

**Comment by craigfowler** [comment]
OK, that clears some things up.

That said, did the HAP have any contributions from anybody who was not the original author? As I understand it you would technically need their permission as well if you want to relicense their work.

Whilst you have an arrangement with the person who did the bulk of the work, that person doesn't have the right to sell other people's contributions (if they exist) to you.

Also, the license file mentions a 'pro' version which uses a non-open-source license. I presume that there won't be any code which is not open-source going into this github repo? If a 'pro' version is released, then its code will be managed independently of this repo?

Thanks, and sorry for the slew of questions but I have a vested interest in the HAP as I use it to support a project of my own. I was previously considering forking it myself. If be willing instead to work with this version going forward, as long as it's safe to do so and I'm not risking a takedown/legal challenge.

**Comment by JonathanMagnan** [comment]
I removed the "Dual Licensing" part since there is no PRO version. This sentence can only add some confusion, and there is currently no plan to have a "pro" version.

As far as I know, this library has two additional contributors and all what their asking, is to make sure this library stay supported. So I don't think they care the license has been modified to a more permissive license.

I don't believe that you really need to bother with this legal stuff either. The original owner transferred me the full ownership, so I highly believe it's safe and anyway, the legal challenge will go against me and not against you.

Best Regards,

Jonathan

**Comment by craigfowler** [comment]
That's true that any potential challenge wouldn't go against me.  If such a challenge did happen and go against you, and (worst case) this updated version of the HAP was taken down, it would affect any software which was built with a heavy dependency upon the HAP.  So - it is still a risk to me, even though not directly.

Anyway - you have answered all of my questions and I'm happy with the answers.  Thankyou :)

**Comment by JonathanMagnan** [comment]
I still believe you go way too much deeply in the legal stuff…

The only one that can take down a repository related to Html Agility Pack or a purpose to doing such thing is currently me.

Despite having multiple personalities, I trust myself that none of them will try to attempt to do it!

The only reason I changed the license to MIT it’s because almost no one understands fully how to work all this kind of license. Out of 8 repositories, I checked within minutes on GitHub that copied the source, **NONE** of them currently respect the Ms-PL license.

So by changing the license to the must permissive (MIT), I make everyone/company life easier.

Anyway, that’s up to you and your decision, if you want to create your own fork, go ahead ;)

Best Regards,

Jonathan
