### ISSUE TITLE
SelectNodes()/SelectSingleNode() not found.

### ISSUE THREAD

**Issue by MikiraSora** [zzzprojects/html-agility-pack#50]
I have a UWP project and get this library from nuget,but there arent SelectNodes()/SelectSingleNode() Methods in HtmlNode.

**Comment by JonathanMagnan** [comment]
Hello @MikiraSora ,

You are right. It seems all methods that require XPath is not available for UWP project.

We will try to understand why it has never been available before. Perhaps there is a limitation we are not aware of.

Note for us: https://stackoverflow.com/questions/34797606/system-xml-xpath-in-universal-windows-platform

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @MikiraSora ,

We have investigated this issue.

It seems UWP project still reference to DotNet45 lib.

We created a new class UWP class library which works very fine with our UWP project but now the issue is more to look for backward compatibility to make sure releasing this fix will not cause more problem than it solves.

Best Regards,

Jonathan

**Comment by MikiraSora** [comment]
thanks,And I found a [artical ](http://www.cnblogs.com/linezero/p/4709393.html),it needs delete some methods and nuget lib 'System.Xml.XPath.XDocument" for this project . I can use it in my UWP Project successfully,Hope it can help you.:D

**Comment by JonathanMagnan** [comment]
Thank you,

We will sure look at it soon.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @MikiraSora ,

The v1.5.2-beta6 has been released.

It should now support UWP project including support for `SelectNodes`, `SelectSingleNode`

Feel free to re-open if you still have an issue.

Best Regards,

Jonathan
