### ISSUE TITLE
Method not found: '!!0 HtmlAgilityPack.HtmlNode.GetEncapsulatedData()'. in UWP

### ISSUE THREAD

**Issue by hippieZhou** [zzzprojects/html-agility-pack#517]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

## 1. Description
Describe the issue or propose a feature.

when I use newest package(HtmlAgilityPack:1.11.53) in my UWP project, I have this issue:
![image](https://github.com/zzzprojects/html-agility-pack/assets/13598361/6e2f4cd6-7df9-480a-9fbf-628afef2e5c3)

When I try to reference the source code into my project it works fine

## 2. Exception
If you are seeing an exception, include the full exception details (message and stack trace).

![image](https://github.com/zzzprojects/html-agility-pack/assets/13598361/84aee7e3-f8b1-40d0-8fe9-fd7ffbd7b022)

```
Exception message:Method not found: '!!0 HtmlAgilityPack.HtmlNode.GetEncapsulatedData()'.
Stack trace:null
```
![image](https://github.com/zzzprojects/html-agility-pack/assets/13598361/1fb77154-5dc5-4c9f-90d6-22d0fb97892c)

## 3. Fiddle or Project
You can reproduce this exception with this sample
[Mvp.zip](https://github.com/zzzprojects/html-agility-pack/files/12669277/Mvp.zip)

## 4. Any further technical details
Add any relevant detail can help us, such as: 

- HAP version:1.11.53
- NET version (netstandard 2.0)
- UWP version(TargetPlatformMinVersion : 10.0.22621.0)

**Comment by hippieZhou** [comment]
thank you for your reply, i think you right, by the way, is there a better way for this scenario ? I'm confused that why when I add the source code (not package) to my solution, I don't got this exception.

**Comment by elgonzo** [comment]
> is there a better way for this scenario?

I don't know what the scenario is. All i know is that you want to get _some_ data from _some_ HTML (by virtue of calling GetEncapsulatedData), but i don't know what the data, how complex the data and the source HTML is. Perhaps your code could just process the HTML structure directly to obtain the data you want and create the desired data object instances "manually". Whether this is simple or complicated i don't know, because judging this would require knowing what and how much data you need to obtain from where in the source HTML.

>  I'm confused that why when I add the source code (not package) to my solution, I don't got this exception.

I can't say without knowing in detail how exactly you included the HAP source code in your solution. There are too many unknowns regarding this for me to make a reasonable guess. A wild speculation might be that for some reason when using the nuget package, your UWP project (or some other dependency of that project) pulls in the UAP flavor of HtmlAgilityPack, effectively taking priority over the .NETStandard20 flavour the dependency on the class library project wants to pull in. The class library itself is still compiled against the .NETStandard20 flavour of HAP, but at runtime the UAP 10.0 flavour of HAP is present. And when the code in the class library is calling GetEncapsulatedData, the runtime isn't finding that method in the present HAP assembly, because that assembly is the UAP flavour of HAP.

Keep in mind it's just blind speculation on my part here. There might very well be other reasons at play here relating to peculiarities of the UAP/UWP build target and platform i am entirely oblivious about due to my glaring lack of UAP/UWP experience... ;-P

However, also keep in mind that GetEncapsulatedData is a reflection-heavy API, and as such it makes perfect sense to exclude it from the UAP flavour of HtmlAgilityPack due to the limitations of that platform (which stipulates, or perhaps even requires

**Comment by hippieZhou** [comment]
with your explanation, I realized that I need to use manual way to create my web data
