### ISSUE TITLE
LoadHTML leads to wrong result when node begins with underscore

### ISSUE THREAD

**Issue by mausoma** [zzzprojects/html-agility-pack#519]
## 1. Description
Describe the issue or propose a feature.
            var html = @"<root><_links>A</_links></root>";
            
            var htmlInput = new HtmlAgilityPack.HtmlDocument();
            htmlInput.LoadHtml(html);

            Console.WriteLine(html);
            Console.WriteLine(htmlInput.DocumentNode.OuterHtml);

LoadHTML doesn't load the XML correctly. The output is:
<root><_links>A</_links></root>
<root><_links>A</root>

## 2. Exception
I would expect that the input and OuterHTML are (more or less) the same. 
But the end tag of </_links> is missing completely.

## 4. Any further technical details
- HAP version:  1.11.54
- NET Framework  4.7.2

**Comment by JonathanMagnan** [comment]
Hello @mausoma ,

`HtmlAgilityPack` is an `HTML` parser. A tag in `HTML` cannot start with an underscore.

Best Regards,

Jon

**Comment by elgonzo** [comment]
Additionally to what Jonathan already pointed out, i want to point out that it is possible to check whether the input data has been successfully parsed without errors. To do so, check [`HtmlDocument.ParseErrors`](https://github.com/zzzprojects/html-agility-pack/blob/f745398b029ebd458f6aec16d066c7268ae3e4c4/src/HtmlAgilityPack.Shared/HtmlDocument.cs#L313-L316) after loading the input data for any reported error.

In your case, `HtmlDocument.ParseErrors` should contain an error relating to the invalid \<\_links\> element. However, unfortunately the reported error is a bit misleading, as it indicates "_Start tag \<\_links\> was not found_" instead of an error referring to "_\_links_" being an invalid element name. :-(

(P.S.: I am just a user and not affiliated with the HAP project or its maintainers.)
