### ISSUE TITLE
Set PackageLicenseExpression on nuget

### ISSUE THREAD

**Issue by thompson-tomo** [zzzprojects/html-agility-pack#544]
### Summary
I wish for the nuget packages to have the licence expression property set correctly

### Details

The licence expression property should be set to the correct licence type (depending on the repo) as this will enable analysis of licences in use to occur in external tools & the license type will be shown in Nuget etc.

**Comment by JonathanMagnan** [comment]
Hello @thompson-tomo 

I'm not sure what you are trying to say, the current license on NuGet currently points to this URL: https://github.com/zzzprojects/html-agility-pack/blob/master/LICENSE

Let me know more about your concerns.

Best Regards,

Jon

**Comment by thompson-tomo** [comment]
@JonathanMagnan i am using cyclonedx to generate SBOM's of all the libraries i am using and checking licence compliance which leverages the licence expression being set. Also by having it set it becomes easiliy visible in nuget.org

**Comment by JonathanMagnan** [comment]
Oh ok, I understand @thompson-tomo ,

It will be done the next time we release HAP

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @thompson-tomo ,

A new version is now available.

I don't really like it, as we now point to a generic page: https://licenses.nuget.org/MIT instead of the license that include the information, but oh well, since it looks like all majors packages I verified are doing it, I guess we will just stay like this.

Let me know if everything now works on your side.

Best Regards,

Jon

**Comment by thompson-tomo** [comment]
Looks good so will close issue
