### ISSUE TITLE
OptionOutputAsXml  = true since version 1.11.65 crossorigin issue

### ISSUE THREAD

**Issue by EynsherKiel** [zzzprojects/html-agility-pack#569]
Hi there,

I work with xhtml and output as xml is an important feature
```html
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
```

With OptionOutputAsXml in version 1.11.61 rendered to
```html
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="" />
```
But in 1.11.65 
```html
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
```
maybe it's a bug, I don't know, or maybe it should be like that, but xhml can't parse crossorigin without ="", exception message
`Attribute name "crossorigin" associated with an element type "link" must be followed by the ' = ' character`

**Comment by JonathanMagnan** [comment]
Hello @EynsherKiel ,

Thank you for reporting.

Indeed, that issue was recently added, I believe, to the [v1.11.62](https://github.com/zzzprojects/html-agility-pack/releases/tag/v1.11.62). That change is currently causing many unexpected side effects (to the point that I wonder if I should not revert it).

I'm traveling until September 19; it will be fixed when I return.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @EynsherKiel ,

A new version has been released today: https://github.com/zzzprojects/html-agility-pack/releases/tag/v1.11.66

While the fix is not 100% backward compatible with versions prior to v1.11.62 as this is now no longer possible to write an attribute without a quote, it will definitely fix this issue.

Let me know if your issue is fixed.

Best Regards,

Jon
