### ISSUE TITLE
HtmlAttribute.Value

### ISSUE THREAD

**Issue by Mx-Wolf** [zzzprojects/html-agility-pack#76]
var doc = new HtmlDocument();
        var html = doc.CreateElement("span"); 
        html.Attributes.Add("data-marker", null);
        var nullValue = html.Attributes[0].Value;

NullReferenceException at _value = _ownerdocument.**Text**.Substring(_valuestartindex, _valuelength);
**Text** is null.

**Comment by JonathanMagnan** [comment]
Hello @Mx-Wolf ,

Thank you for reporting,

We will look at it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Mx-Wolf ,

We started to investigate, the major problem is what should be the default behavior we are searching.

- Should making an attribute with a null value should remove the attribute from the list like jQuery do?
- Should making an attribute with a null value should put the value "null" as JavaScript do
- Should making an attribute with a null value should put the value "undefined" as `System.Windows.Forms.HtmlDocument` do

Currently, it looks there is no good answer to it.

Is there a reason why you set it to null?

Best Regards,

Jonathan

**Comment by Mx-Wolf** [comment]
Hi Jonathan,
May I suggest that the issue is with the `HtmlAttributeCollection.Add` method. Once you allow to set some value of an attribute, you should allow to read its value as well. Whatever it is. The behavior for the object with null-ed attribute value is out of the scope.
That is in your `Add` method you might start checking to see if latter reading will succeed and throw an `ArgumentException` if it is not.

**Comment by JonathanMagnan** [comment]
Hello @Mx-Wolf ,

That's not exactly out of scope (or perhaps I misinterpreted your sentence) since when an attribute is added, it's also added to the document text which is how the value is read after. 

I believe the default behavior should be simply not do show the attribute in the document text since it's null and handle the `Value` property to return null.

I'm supposed to release a new version of HAP today, I will try to add this fix on this version as well.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Mx-Wolf ,

The v1.5.6-beta3 has been released

You should no longer have this null value issue.

Best Regards,

Jonathan

**Comment by Mx-Wolf** [comment]
Thank you. Indeed no NullReferenceException thrown
