### ISSUE TITLE
When Using OptionOutputOriginalCase and OptionOutputAsXml, Upper Case Tags Are Messed Up

### ISSUE THREAD

**Issue by mbrierst** [zzzprojects/html-agility-pack#85]
Like the title says.  Here's a demo in C#:
```C#
// Remove either option for better behavior
var htmlDocument = new HtmlDocument { OptionOutputOriginalCase = true, OptionOutputAsXml = true };
htmlDocument.LoadHtml("<DIV></DIV>");
MessageBox.Show(htmlDocument.DocumentNode.InnerHtml);
```

**Comment by JonathanMagnan** [comment]
Hello @mbrierst ,

Thank you for reporting, I will investigate this issue today.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Wow... there are more than messed up!

The problem seems that the method `GetXmlName` is case sensitive and doesn't support uppercase.

Already fixed but I need to make sure that will not cause any side impact.

This fix will be included in the version that will be released later today or tomorrow.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @mbrierst ,

The v1.6.0 has been released,

The casing issue should be fixed

Please reopen if you still have the issue.

Best Regards,

Jonathan

**Comment by mbrierst** [comment]
Looks like it's fixed.  Thanks!
