### ISSUE TITLE
XPath from Chrome can't be found

### ISSUE THREAD

**Issue by playgithub** [zzzprojects/html-agility-pack#9]
WebSite: http://quotes.money.163.com/1000527.html
xpath: /html/body/div[2]/div[1]/div[3]/table/tbody/tr/td[2]/div/table/tbody/tr[1]/td[1]/span
what xpath tries to locate is in the red box in the image below
![untitled](https://cloud.githubusercontent.com/assets/3665590/26554083/1c503ed4-44c1-11e7-865b-52d165333fe5.png)

**Comment by JonathanMagnan** [comment]
Hello @playgithub ,

```csharp
string url = @"http://quotes.money.163.com/1000527.html";
       
HtmlWeb web = new HtmlWeb();
HtmlAgilityPack.HtmlDocument doc = web.Load(url);

// Full Path
var test1 = doc.DocumentNode.SelectSingleNode("/html[1]/body[1]/div[2]/div[1]/div[3]/table[1]/tr[1]/td[2]/div[1]/table[1]/tr[1]/td[1]/span[1]");

// By class name
var test2 = doc.DocumentNode.SelectSingleNode("//span[contains(@class, 'sotck_closed')]");
var innerText = test2.InnerText;
```

Let me know if that's what you are looking for

Best Regards,

Jonathan

**Comment by playgithub** [comment]
Thanks, both works well.
Why the XPath copied out from Chrome doesn't work directly? Isn't it non-standard?

**Comment by JonathanMagnan** [comment]
> 1. Which is faster? Full path or By class name?

Is this very important? Both are very fast, and the tick difference is probably not a bottom neck for your application.

Use the one you prefer. From my part, I would use the CSS.

The reason is simple. The HTML/XPath have more chance to be changed than the class name. When making a design change, we add additional div, span, etc, but we often keep the same class name.

So the real question is which one have less chance to be changed?

> 2. Why doesn't the XPath copied out from Chrome work directly? Isn't it non-standard?
The problem is browser are fixing && adding a tag which HAP doesn't do.

The original HTML look like this:

```html
<table>
	<tr>
		<td class="price"><span class="sotck_closed">已退市</span></td>
```

The chrome/ie/firefox html look like this:
```html
<table>
	<tbody>
		<tr>
			<td class="price"><span class="sotck_closed">已退市</span></td>
```

The browser has automatically added a 'tbody' tag. So the HTML you see from the Chrome source is different from the original source.

If you simply remove the `tbody` from the XPath, it will work correctly

```
/html/body/div[2]/div[1]/div[3]/table/tr/td[2]/div/table/tr[1]/td[1]/span
```

Let me know if that answer correctly to your both questions.

Best Regards,

Jonathan

**Comment by playgithub** [comment]
Thanks very very much.

**Comment by playgithub** [comment]
Any convenient way to find XPath for HAP ?

**Comment by JonathanMagnan** [comment]
Hello @playgithub ,

What do you mean? You can find the XPath from the node and you find it... but at this point, you already find it.

If you have something in mind, let us know and we will evaluate this request.

Best Regards,

Jonathan

**Comment by playgithub** [comment]
I mean whether there is a quick way to find the XPath for a node for the original webpage.

**Comment by JonathanMagnan** [comment]
Hello @playgithub ,

Unfortunately no, we could try to create a helper application (A little bit like developer tools you use for Chrome), but there is nothing such like this in our roadmap.

We will start soon to create articles about XPath and provide a CSS selector. It will become easier to find it by following some best practices and tips.

Best Regards,

Jonathan
