### ISSUE TITLE
Question About the Code

### ISSUE THREAD

**Issue by SoftCircuits** [zzzprojects/html-agility-pack#91]
I've been reviewing the code, trying to understand some details of how it works. But I was unable to figure out the following. Can anyone help?

How would the following HTML be handled?

    <p>Text<h1>More Text

I assume that the `<h1>` tag should terminate the `<p>` tag because nesting an `<h1>` within a `<p>` is not valid. But what does HTML Agility Pack do, and more important, where is the code that would detect and handle such a case? I couldn't find it.

**Comment by JonathanMagnan** [comment]
Hello @SoftCircuits ,

This kind of scenario are currently not supported. That's why you don't find the code and why I'm often talking about the v2.x which will be HTML5 compatible.

Currently, the weak logic that exists can be found here: https://github.com/zzzprojects/html-agility-pack/blob/master/src/HtmlAgilityPack.Shared/HtmlDocument.cs#L1615

The parser that I would like to use for the v2.x already exists and is already HTML5 compatible.

Let me know if that answer correctly to your question.

Best Regards,

Jonathan

**Comment by SoftCircuits** [comment]
Thanks for the info.

Just FYI, for me, it's not so much the place of the parser to enforce proper HTML structure (such as not allowing `<h1>` within `<p>` elements) as it is to more intelligently handle mismatched open and closing tags. I'll check out the link.

Thanks again.

**Comment by JonathanMagnan** [comment]
Hello @SoftCircuits ,

We are currently making some issue cleanup.

Feel free to reopen if I closed this one by mistake.

Best Regards,

Jonathan

---
_Help us to keep this library free: [Donate](http://www.zzzprojects.com/contribute)_
